name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Debug dependencies
        run: |
          pip list
          python --version
          pylint --version

      - name: Run tests (no coverage)
        run: python -m pytest tests/

      - name: Run pylint and coverage report
        run: |
          pylint calculator
          python -m pytest --cov=calculator --cov-report=term-missing
